import = ["/home/johan/.config/alacritty/nord.toml"]

[cursor]
thickness = 0.25

[cursor.style]
blinking = "Off"
shape = "Block"

[font]
size = 12.0

[font.normal]
family = "Iosevka NF"
style = "Regular"

[mouse]
hide_when_typing = false

[scrolling]
history = 10000

[selection]
semantic_escape_chars = "=,│`|:\"' ()[]{}<>\t*"

[window.padding]
x = 2
y = 2
