add_newline = false

format = """
$all$fill$time
$character"""

[fill]
symbol = " "

[character]
success_symbol = "[\\$](bold green)"
error_symbol = "[\\$](bold red)"

[directory]
truncate_to_repo = false

[cmake]
disabled = true

[lua]
disabled = true

[package]
disabled = true

[python]
symbol = "\ue73c "
style = "purple bold"

[time]
disabled = false
format = "[$time](blue)"

[line_break]
disabled = true
