set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g mouse on
set -g set-clipboard on
set -g allow-passthrough on
set -g history-limit 50000

# Change from 0 based to 1 based numbering
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1
set -g renumber-windows on   

set -g mode-keys vi
set -g word-separators " |{}()[]<>`='\"!@#$%^&*:;,?"

run "~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux"

thm_bg="#1e1e2e"
thm_fg="#ebdbb2"
thm_cyan="#89dceb"
thm_gray="#45475a"
thm_maroon="#eba0ac"
thm_blue="#89b4fa"
thm_orange="#fab387"
thm_green="#a6e3a1"

# Status bar
set -g status-position top
set -g status-left-length "100"
set -g status-style "fg=${thm_gray},bg=default"
set -g status-left "#[fg=${thm_green},bold]  #S #[fg=${thm_gray},nobold] | "
set -g status-right ""
set -g status "on"
set -g status-justify "left"
set -g status-right-length "100"

# Messages
set -g message-style "fg=${thm_cyan},bg=${thm_gray},align=centre"

# Panes
set -g pane-border-style "fg=${thm_gray}"
set -g pane-active-border-style "fg=${thm_blue}"

# Windows
set -g window-status-current-format "#[fg=${thm_blue},bg=${thm_bg},bold] #[underscore]#I:#W"
set -g window-status-format " #I:#W"

# Fix the status bar
set -g status-interval 5

#############
# KEYBINDINGS

#unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Vim style pane selection
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind -n C-h if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
bind -n C-j if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
bind -n C-k if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind -n C-l if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'

bind r source-file "~/.config/tmux/tmux.conf" \; display "Reloaded tmux configuration"
bind b set -g status
bind f run "tmux neww ~/.local/bin/tmux-sessionizer.sh"
bind g run "~/.local/bin/open-github.sh"
bind N run "~/.local/bin/tmux-sessionizer.sh ~/Documents"
bind C run "~/.local/bin/tmux-sessionizer.sh ~/.config"
bind H run "~/.local/bin/tmux-sessionizer.sh ~"
bind T run "~/.local/bin/tmux-sessionizer.sh ~/projects/tracer"
bind E show-environment -g

# Popups
bind C-f display-popup \
  -w 80% \
  -h 80% \
  -E 'rmpc'
bind C-e display-popup \
  -w 80% \
  -h 80% \
  -E 'nvim ~/.config/tmux/tmux.conf'
bind C-t display-popup \
  -d "#{pane_current_path}" \
  -w 75% \
  -h 75% \
  -E "bash"

