set -g default-terminal "tmux-256color"
set -ga terminal-overrides ",*:RGB"
set -g mouse on
set -g set-clipboard on
set -g allow-passthrough on
set -g history-limit 50000
set -s copy-command 'wl-copy -pn'

# Change from 0 based to 1 based numbering
set -g base-index 1
set -g pane-base-index 1
set-window-option -g pane-base-index 1

set -g renumber-windows off
set-window-option -g automatic-rename on

set -g mode-keys vi
set -g word-separators " |{}()[]<>`='\"!@#$%^&*:;,?"

#run "~/.config/tmux/plugins/catppuccin/tmux/catppuccin.tmux"

thm_bg="#1e1e2e"
thm_fg="#ebdbb2"
thm_cyan="#89dceb"
thm_gray="#45475a"
thm_maroon="#eba0ac"
thm_blue="#89b4fa"
thm_orange="#fab387"
thm_green="#a6e3a1"

# Status bar
set -g status-position top
set -g status-left-length "100"
set -g status-style "fg=${thm_gray},bg=default"
set -g status-left "#[bg=${thm_green},fg=${thm_bg},bold]  #S #[fg=${thm_green},bg=default,nobold] "
set -g status-right "#[fg=${thm_gray},bg=default,nobold]#[bg=${thm_gray},fg=${thm_blue},nobold] 󰋊 : #{df_avail}/#{df_percent} #[fg=${thm_blue},bg=${thm_gray},bold]#[bg=${thm_blue},fg=${thm_bg},bold] # : #{cpu_percentage} "
set -g status "on"
set -g status-justify "left"
set -g status-right-length "100"

# Messages
set -g message-style "fg=${thm_cyan},bg=${thm_gray},align=centre"

# Panes
set -g pane-border-style "fg=${thm_gray}"
set -g pane-active-border-style "fg=${thm_blue}"

# Windows
set -g window-status-current-format "#[fg=${thm_blue},bg=${thm_bg},bold] #[underscore]#I:#W"
set -g window-status-format " #I:#W"

# Fix the status bar
set -g status-interval 5

#############
# KEYBINDINGS

#unbind C-b
set -g prefix C-Space
bind C-Space send-prefix

# Vim style pane selection
is_vim="ps -o state= -o comm= -t '#{pane_tty}' | grep -iqE '^[^TXZ ]+ +(\\S+\\/)?g?(view|n?vim?x?)(diff)?$'"
bind -n C-h if-shell "$is_vim" 'send-keys C-h' 'select-pane -L'
bind -n C-j if-shell "$is_vim" 'send-keys C-j' 'select-pane -D'
bind -n C-k if-shell "$is_vim" 'send-keys C-k' 'select-pane -U'
bind -n C-l if-shell "$is_vim" 'send-keys C-l' 'select-pane -R'

bind C-k send-keys C-k
bind C-l send-keys C-l

bind-key -T copy-mode-vi MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "wl-copy -pn && wl-copy -n"
bind-key -T copy-mode    MouseDragEnd1Pane send-keys -X copy-pipe-and-cancel "wl-copy -pn && wl-copy -n"
bind-key -n MouseDown2Pane run "tmux set-buffer -b primary_selection \"$(wl-paste -p)\"; tmux paste-buffer -b primary_selection; tmux delete-buffer -b primary_selection"
bind -n S-Pageup if-shell "$is_vim" 'send-keys Pageup' 'copy-mode -u'
bind -n S-Pagedown send-keys Pagedown
bind-key -n C-d if-shell "echo '#{pane_current_command}' | grep -iqE '^(bash|zsh|fish)$'" \
    "detach-client" \
    "send-keys C-d"

bind r source-file "~/.config/tmux/tmux.conf" \; display "Reloaded tmux configuration"
bind b set -g status
bind f run "tmux neww ~/.local/bin/tmux-sessionizer.sh"
bind g run "~/.local/bin/open-github.sh"
bind N run "~/.local/bin/tmux-sessionizer.sh ~/Documents"
bind C run "~/.local/bin/tmux-sessionizer.sh ~/.config"
bind H run "~/.local/bin/tmux-sessionizer.sh ~"
bind T run "~/.local/bin/tmux-sessionizer.sh ~/projects/tracer"
bind E show-environment -g

bind-key -T copy-mode-vi v send-keys -X begin-selection
bind-key -T copy-mode-vi C-v send-keys -X rectangle-toggle
bind-key -T copy-mode-vi y send-keys -X copy-selection-and-cancel

# Popups
bind C-e display-popup \
  -w 80% \
  -h 80% \
  -E 'nvim ~/.config/tmux/tmux.conf'
bind C-t display-popup \
  -d "#{pane_current_path}" \
  -w 75% \
  -h 75% \
  -E "bash"

set -g @plugin 'tmux-plugins/tpm'
set -g @plugin 'tmux-plugins/tmux-cpu'
set -g @plugin 'tassaron/tmux-df'
set -g @plugin 'sainnhe/tmux-fzf'
set -g @plugin 'roosta/tmux-fuzzback'

set -g @cpu_percentage_format "%4.1f%%" 

set -g @fuzzback-hide-preview 1
set -g @fuzzback-popup 1

run '~/.config/tmux/plugins/tpm/tpm'

